POST http://localhost:3000/
content-type: application/json

{
  "peso": 56
}

###
POST http://localhost:3000/
content-type: application/json

{
  "proximidad": 14
}

###
GET http://localhost:3000/

###
GET http://localhost:3000/analyzed

###
GET http://localhost:3000/analyzed/avg

###
GET http://localhost:3000/analyzed/actual

###
GET http://localhost:3000/analyzed/uso

###
GET http://localhost:3000/analyzed/09-14-2021
